# Generated by Django 3.2.13 on 2022-10-06 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='completed',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
