# Generated by Django 3.2.13 on 2022-10-07 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Model',
            new_name='Movie',
        ),
    ]
